### ISSUE TITLE
.NET 8 Isolated function do not startup on Azure environment

### ISSUE THREAD

**Issue by igor-henriques** [Azure/azure-functions-dotnet-worker#2535]
### Description

I'm using an Azure Function .NET 8 Isolated (upgraded from .NET 6 template) and also using the official `AzureFunctionApp@2` pipeline deploy task to handle the deployment. Locally everything runs fine without any issue, but when deployed I'm seeing this error: 

> Microsoft.Azure.WebJobs.Script.ExternalStartupException : Error configuring services in an external startup class. ---> System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore.Routing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified

This is my deploy stage:

```
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      name: 'SelfHostedAgentPool'
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@2
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: $(functionAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
```

The thing is, I don't even have that `.dll` in my output folder, although I have the package as a dependency from Microsoft.Azure.WebJobs.Extensions.Http (3.2.0), which in turn is a dependency of Microsoft.NET.Sdk.Functions (4.0.0).

![image](https://github.com/Azure/azure-functions-dotnet-worker/assets/54086793/feb8aca3-4e13-4d7d-9807-bb4667cddf0f)

and guess what, I can't downgrade to a non-deprecated version (what?!) because it is a dependency of a major package, and I can't also see that dll in my output folder as well.

Plus: the template offered by VS (2022) didn't even include the package that is causing the issue here on this topic: Microsoft.Azure.Functions.Worker.Extensions.ServiceBus

All packages I have now are:

```
<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.17.5" />
<PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.16.1" />
<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.4.0" />
<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
<PackageReference Include="Polly" Version="8.4.0" />
<PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
<PackageReference Include="Twilio" Version="7.1.1" />
```

So, indeed, the root cause here, at least for me, is Microsoft.NET.Sdk.Functions, which I can't just downgrade because all non-deprecated versions still has that same dependency chain that end up needing the same Microsoft.AspNetCore.Routing, Version=7.0.0 package

This issue might be related to https://github.com/Azure/azure-functions-dotnet-worker/issues/2270, but, as apparently no one gave the required attention to that one, I'm also raising this.

**THIS IS AN ISSUE!!**

### Steps to reproduce

1. Create a .NET 6 Isolated azure function template triggered by Service Bus
2. Upgrade the version to .NET 8
3. Upgrade the packages
4. Deploy (I haven't tested with a publish profile, only pipeline)
5. See the error
