### ISSUE TITLE
Fix and Re-enable `Worker.ApplicationInsights.Tests`

### ISSUE THREAD

**Issue by satvu** [Azure/azure-functions-dotnet-worker#2780]
While fixing typos to reenable tests in https://github.com/Azure/azure-functions-dotnet-worker/pull/2773, it was discovered that this test suite was failing to build and run. Creating a separate issue to investigate these tests and reenable them. Once reenabled, they need to be added to `eng/ci/templates/jobs/run-unit-tests.yml`:

```
- task: DotNetCoreCLI@2
    displayName: Application Insights Tests
    inputs:
      command: test
      arguments: -v n
      projects: |
        **\Worker.ApplicationInsights.Tests.csproj
```
