### ISSUE TITLE
microsoft.azure.functions.worker.sdk 2.0.3 fail dotnet publish command

### ISSUE THREAD

**Issue by randy9527** [Azure/azure-functions-dotnet-worker#3067]
### Description

Under .Net 8.0, microsoft.azure.functions.worker.sdk 2.0.3 caused dotnet publish command to fail. Worked well in 2.0.2.

### Steps to reproduce

Running this command:
`C:\hostedtoolcache\windows\dotnet\dotnet.exe publish some.csproj --configuration debug --output somefolder --no-build`

results below error:
`C:\Users\VssAdministrator\.nuget\packages\microsoft.azure.functions.worker.sdk\2.0.3\build\Microsoft.Azure.Functions.Worker.Sdk.targets(234,5): error MSB4044: The "AssignTargetPath" task was not given a value for the required parameter "RootFolder".`

**Comment by lupusbytes** [comment]
Same thing happens in all 3 of our .NET 9.0 function projects.
Build and tests work fine, but the the publish command fails.

```
  - task: DotNetCoreCLI@2
    displayName: .NET publish Functions
    inputs:
      command: publish
      publishWebProjects: false
      arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/packages'
      projects: src/redacted/redacted.csproj
      zipAfterPublish: true
```
Error:
`/home/vsts/.nuget/packages/microsoft.azure.functions.worker.sdk/2.0.3/build/Microsoft.Azure.Functions.Worker.Sdk.targets(234,5): error MSB4044: The "AssignTargetPath" task was not given a value for the required parameter "RootFolder" ...`

Downgrading to Microsoft.Azure.Functions.Worker.Sdk 2.0.2 fixes the problem
