### ISSUE TITLE
Azure support for .NET 5 Function Apps (Pipeline and portal)

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-functions-dotnet-worker#536]
I got here from https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

I've looked around but I'm not really sure where this should go, sorry if this is the wrong place.

I have been fighting Azure DevOps (ADO) with a test .NET 5 isolated Function App for a while now, trying to get it to work through ADO. I know it's not officially supported, and I don't expect it to work; I am trying to hack something together to preserve our workflow, otherwise .NET 5 is basically dead for us. I've been trying to deploy files/zips directly, use dotnet/VS publish commands & profiles, blah blah and nothing works so far. (Deploying straight from VS works as described in the docs.)

Relatedly, I needed to create the Function App through VS, there was no way I found to do it through the portal (I suspect the API works and is what VS uses).

My question is: is this support intended to happen? Is it underway, planned or on a roadmap? Is there portal support for .NET 5 isolated FuncApps planned as well?

Any routing help or pointers to communication that confirms this support is planned would be appreciated.

**Comment by brettsam** [comment]
It's certainly possible to deploy with DevOps, but I don't think any of the built-in tasks do this today. I'm assigning to @anthonychu to work on a sample/docs for this.

And yes, the portal work is planned -- but we have no ETA for this at the moment.

**Comment by anthonychu** [comment]
@josh-endries I tried this out and it works. I used a Windows consumption app.

The steps described [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops?tabs=csharp%2Cwindows) should work.

There is one added detail that you must set the `FUNCTIONS_WORKER_RUNTIME` app setting to `dotnet-isolated`. You can either manually do this in the portal, or set it in the `AzureFunctionApp@1` task (see below).

Here's the pipeline I tested with:

```yml
trigger:
- azure-devops

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration Release --output publish_output'
    projects: '*.csproj'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
    includeRootFolder: false
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'my-service-connection-name'
    appType: 'functionApp'
    appName: 'my-function-app-name'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    appSettings: '-FUNCTIONS_WORKER_RUNTIME dotnet-isolated'
    deploymentMethod: 'runFromPackage'
```

\+ @ggailey777 for thoughts on how to incorporate this into docs.
